osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx travis-deploy-once "npx semantic-release"
  on:
    repo: Slurp/sheepmusic-app
- provider: releases
  api_key:
    secure: J+dLvaler7qKA0odZnyhFwI1wFaHVrp5AbtSZykTNj/ki57f1+XVylxOwgAP4b+Nl3UxRUg/j7ValWfESNf5fu4OHqE2k3QAzhmXL1z66p2VzVFGjpsnaOlhkbnuDqgqT0AQDaS/kW7db0/UwNVvdjWQJlEBvsuM8MRxsX2BwlnbjInw5WaGgfctSA2hkOd79DL1NbZ4EoPQZWXJO5FBvjy7dwcPcOiWTYz4mC4zkHD/dTKBODKCtdEszXUqGfMlTO6/kLzuo2E2ktnhuBRCUCaI2IHTdmPeuFHx4hiC4e3PEtokl/btCfqonFTSmz3HqW9HJcpnEJdHzYR1GRUJXoch8Iky/T3biBVm+2raMqe7qDsAUUexY7y2KvkFtb8f8PEslHTWe24lDKncjxAl+CGCGv9/ulMMjwXu1HgXQ6QVjRIYCDansjm1bSNdRs/U0XbHbYLgfru/WftTeWnpOQox2GnevivOD9uBGGZshECfTY558CHVFnNaTacFf5Q+EiKmwq8A5Ir4XuYOVb3XisoMnmi663t7zVEaDFxq3nIMsglXNkZZ8wj8+TgFUKP2OxnZOXj7/WBlZa1qKZPY65aolTP3h1pr72a0jFaEG64HJTVFRMF+fyTC9WUPkPE7KWJLSv9uwQZDp6MGWeQNmSEF7HzzUQKgjBdwrn4hbKo=
  file: build/mac/*
  on:
    repo: Slurp/sheepmusic-app
